### ISSUE TITLE
Enable federated SPARQL queries per default

### ISSUE THREAD

**Issue by holycrab13** [dbpedia/gstore#12]
Start virutoso with the appropriate settings or let the gstore change the settings on the virtuoso after startup
Permissions that need to be granted:

```
grant SPARQL_LOAD_SERVICE_DATA to "SPARQL";
grant SPARQL_SPONGE to "SPARQL";
```

**Comment by manonthegithub** [comment]
example of a query:
```
PREFIX dbo: <http://dbpedia.org/ontology/>

SELECT * WHERE {
  
  SERVICE <http://dbpedia.org/sparql> { 
    {
      SELECT DISTINCT ?city WHERE {
    	  ?city a dbo:City .
      } LIMIT 10
    }
  }
}

**Comment by manonthegithub** [comment]
this can be done in a few ways.
- we can run a script in a separate image (it starts, runs the script and goes down) in docker-compose
- we can try to make our own image based on OpenLink's image which will do it during startup
@holycrab13 What do you think is better?

**Comment by manonthegithub** [comment]
@holycrab13 should work with latest commits... please check :), feel free to reopen in case of problems
