### ISSUE TITLE
add report as jsonld

### ISSUE THREAD

**Issue by holycrab13** [dbpedia/gstore#14]
Using http error codes to determine the result of a SHACL validation feels very weird. Is this something we should discuss?

A failed SHACL validation returns a 400 currentlly, which suggests a wrong user input.
However, a SHACL validation can fail successfuly (fail, when failure is expected)

In my opinion, 400 should be reserved for actually bad input data (not parseable, wrong parameters, missing parameters)
Correct input data should always return a 200 with a json object containing the result in a well-formatted manner, e.g:

```
{
   success: false,
   messages: [
      'violation 1',
      'violation 2'
  ]
}
```

or even better, the SHACL validation report as JSONLD.

**Comment by manonthegithub** [comment]
Good idea! I can implement this, if there are no objections from Sebastian.

Kind regards / Mit freundlichen Grüßen,
Kirill Yankov.

**Comment by manonthegithub** [comment]
the return codes were changed as discussed. the report in a form of jsonld needs to be added. Now report is returned as a multiline string.

**Comment by manonthegithub** [comment]
done in latest commit, now the report is returned in RDF
