### ISSUE TITLE
graph identifier has local gstore URI

### ISSUE THREAD

**Issue by JJ-Author** [dbpedia/gstore#26]
see e.g. https://dev.databus.dbpedia.org/sparql?default-graph-uri=&query=select+distinct+%3Fg+where+%7B+graph+%3Fg+%7B%5B%5D+a+%3FConcept%7D%7D+LIMIT+10&format=text%2Fhtml&timeout=0&signal_void=on 

http://gstore:8080/g/janfo/test/publishing/2022-06-29/dataid.jsonld 

should be the IRI of the jsonld file such that it can be accessed

for more questions refer to @Eisenbahnplatte

**Comment by manonthegithub** [comment]
@JJ-Author @Eisenbahnplatte for that you need to set prefix parameter while uploading data id

<img width="1051" alt="Screenshot 2022-10-19 at 12 29 38" src="https://user-images.githubusercontent.com/10817016/196667919-72e2cd9f-3c6e-46d7-9d91-bc4f2f8c81ed.png">
