### ISSUE TITLE
retrieval of jsonld broken

### ISSUE THREAD

**Issue by holycrab13** [dbpedia/gstore#31]
cannot retrieve internal webids or other jsonld documents from gstore

example:
http://localhost:3002/graph/read?repo=janfo&path=webid.jsonld

error
com.github.jsonldjava.core.JsonLdError: loading remote context failed: %7BprimaryTopic%3D%7B%40id%3Dhttp://xmlns.com/foaf/0.1/primaryTopic,%20@type=@id%7D,%20maker=%7B@id=http://xmlns.com/foaf/0.1/maker,%20@type=@id%7D,%20modulus=%7B@id=http://www.w3.org/ns/auth/cert#modulus%7D,%20exponent=%7B@id=http://www.w3.org/ns/auth/cert%23exponent,%20@type=http://www.w3.org/2001/XMLSchema%23integer%7D,%20label=%7B@id=http://www.w3.org/2000/01/rdf-schema%23label%7D,%20name=%7B@id=http://xmlns.com/foaf/0.1/name%7D,%20account=%7B@id=http://xmlns.com/foaf/0.1/account,%20@type=@id%7D,%20key=%7B@id=http://www.w3.org/ns/auth/cert%23key,%20@type=@id%7D,%20dbo=http://dbpedia.org/ontology/,%20sec=https://w3id.org/security%23,%20dataid=http://dataid.dbpedia.org/ns/core%23,%20dct=http://purl.org/dc/terms/,%20dcv=http://dataid.dbpedia.org/ns/cv%23,%20xsd=http://www.w3.org/2001/XMLSchema%23,%20rdfs=http://www.w3.org/2000/01/rdf-schema%23,%20cert=http://www.w3.org/ns/auth/cert%23,%20dcat=http://www.w3.org/ns/dcat%23,%20foaf=http://xmlns.com/foaf/0.1/%7D

remote context at https://downloads.dbpedia.org/databus/context.jsonld is still online.

**Comment by manonthegithub** [comment]
@holycrab13 should be fixed. please check

**Comment by JJ-Author** [comment]
sry wrong issue

**Comment by holycrab13** [comment]
seems to be unrelated or only occur for insanely huge metadata files

**Comment by holycrab13** [comment]
normal retrieval does work, which was broken as described in this issue

**Comment by manonthegithub** [comment]
@JJ-Author this returns another error not connected to this issue

**Comment by manonthegithub** [comment]
@JJ-Author I guess you commented on the wrong issue
