### ISSUE TITLE
Get on empty Gstore Fails with 500 instead of 404

### ISSUE THREAD

**Issue by holycrab13** [dbpedia/gstore#32]
Get request on a resource in a non-existing repo returns a 500 
"org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /gstore/git/tester"

Expected behaviour:
Return code is a 404 Not Found

**Comment by manonthegithub** [comment]
<img width="848" alt="image" src="https://user-images.githubusercontent.com/10817016/214391150-dcf4be44-118e-4f7d-9684-e26d13ca79c6.png">
Looool :)

**Comment by manonthegithub** [comment]
must work now :)

**Comment by manonthegithub** [comment]
in dev branch
