### ISSUE TITLE
Graph ID needs to match some other URI

### ISSUE THREAD

**Issue by kurzum** [dbpedia/gstore#4]
added a test for graphname in https://github.com/dbpedia/gstore/blob/dev/tests/test_api_functionality.sh#L91
```
ASK { GRAPH <http://localhost:3002/graph/janni/testing/group> {?s ?p ?o} }"
Test curl -s "localhost:3002/sparql?default-graph-uri=&query=ASK%20%7b%20GRAPH%20%3chttp%3a%2f%2flocalhost3002%2fgraph%2fjanni%2ftesting%2fgroup%3e%20%7b%3fs%20%3fp%20%3fo%7d%20%7d" 
✖ false == true :: Virtuoso SPARQL ASK for GRAPH <http://localhost3002/graph/janni/testing/group>
```
Implementation
GRAPH name is always: `<$prefix/$repo/$path>`
1. Default (no prefix parameter): $prefix=$REQUEST_BASE_FQDN/g/$repo/$path 
2. if $prefix is set then graph is <$prefix/$repo/$path>

**Comment by manonthegithub** [comment]
@kurzum hmmm... looks like 3003 is a port of databus, and 3002 is a port of gstore... which one should be used?

**Comment by manonthegithub** [comment]
done, feel free to open if there are some issues
