### ISSUE TITLE
Base content type detection on content-type header of request instead of file ending

### ISSUE THREAD

**Issue by holycrab13** [dbpedia/gstore#42]
The file ending is mandatory at the moment as it is used for content type detection and does not allow saving at arbitrary locations. 

Would it be possible to use the content type header instead?

**Comment by manonthegithub** [comment]
No. If it were possible, I would have done that.

**Comment by holycrab13** [comment]
Ok, a document format must be detectable always, not only at the time of the request - thus file endings mandatory.

**Comment by manonthegithub** [comment]
https://github.com/dbpedia/gstore/issues/38#issuecomment-2161025052
