### ISSUE TITLE
Save files always in jsonld

### ISSUE THREAD

**Issue by manonthegithub** [dbpedia/gstore#6]
Determine the format from Content-Type

**Comment by kurzum** [comment]
added tests for this at https://github.com/dbpedia/gstore/blob/dev/tests/test_api_functionality.sh#L13  and https://github.com/dbpedia/gstore/blob/dev/tests/test_api_functionality.sh#L46

**Comment by manonthegithub** [comment]
done, feel free to open if something is wrong
